<?php if (null !== $block->getLicenseId()): ?>
<script src = "<?php echo $block->getUrl('livechat/getvisitor'); ?>"></script>
<script>
  window.__lc = window.__lc || {};
  window.__lc.integration_name = "magento";
  window.__lc.product_name = "livechat";
  window.__lc.license = <?php echo $block->getLicenseId() ?>;
  if(livechat_visitor_data) {
    window.__lc.visitor = livechat_visitor_data;
  }

  ;(function(n,t,c){function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}var e={_q:[],_h:null,_v:"2.0",on:function(){i(["on",c.call(arguments)])},once:function(){i(["once",c.call(arguments)])},off:function(){i(["off",c.call(arguments)])},get:function(){if(!e._h)throw new Error("[LiveChatWidget] You can't use getters before load.");return i(["get",c.call(arguments)])},call:function(){i(["call",c.call(arguments)])},init:function(){var n=t.createElement("script");n.async=!0,n.type="text/javascript",n.src="https://cdn.livechatinc.com/tracking.js",t.head.appendChild(n)}};!n.__lc.asyncInit&&e.init(),n.LiveChatWidget=n.LiveChatWidget||e}(window,document,[].slice))

  <?php if ($block->isCartSet()): ?>
    var LC_API = LC_API || {};
    LC_API.on_after_load = function() {
        require(['Magento_Customer/js/customer-data'], function (customerData) {
            var cart = customerData.get('cart');
            var count = cart().summary_count;

            if(localStorage) {
              var storageCount = localStorage.getItem('lcCount');
              if(parseInt(storageCount) !== count) {
                getCart();
              }
              localStorage.setItem('lcCount', count);
            }

            var count = cart().summary_count;
            cart.subscribe(function () {
                if (cart().summary_count !== count) {
                    getCart();
                    if(localStorage) {
                      localStorage.setItem('lcCount', cart().summary_count);
                    }
                }
            });
        });
    }

    function getCart() {
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            var customVariables = JSON.parse(this.responseText);

            if (customVariables.length <= 0) {
                customVariables = [{"name":"Cart", "value":"customer's cart is empty"}];
            }

            LC_API.set_custom_variables(customVariables);
        }
      };
      xhttp.open("GET", "<?php echo $block->getUrl('livechat/getcart'); ?>"+"?success=<?php echo $block->isOrderPlacedPage() ?>", true);
      xhttp.send();
    }

  <?php endif; ?>
</script>
<?php else: ?>
<script>
  console.log('Please go to "Stores => Settings => Configuration" and configure your LiveChat account.');
</script>
<?php endif; ?>
