<?php if (null !== $block->getLicenseId()): ?>
<script src = "<?php echo $block->getUrl('livechat/getcart'); ?>"></script>
<script src = "<?php echo $block->getUrl('livechat/getvisitor'); ?>"></script>
<script>
  window.__lc = window.__lc || {};
  window.__lc.license = <?php echo $block->getLicenseId() ?>;

  if(livechat_visitor_data) {
    window.__lc.visitor = livechat_visitor_data;
  }

  (function() {
    var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
    lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
  })(); 

  if(livechat_custom_variables && livechat_custom_variables.length > 0) {
    var LC_API = LC_API || {};
    LC_API.on_after_load = function() {
      LC_API.set_custom_variables(livechat_custom_variables);
    }
  }
</script>
<?php else: ?>
  console.log('Please go to "Stores => Settings => Configuration" and configure your LiveChat account.');
<?php endif; ?>
