<?php if (null !== $block->getLicenseId()): ?>
<script src = "<?php echo $block->getUrl('livechat/getvisitor'); ?>"></script>
<script>
  window.__lc = window.__lc || {};
  window.__lc.license = <?php echo $block->getLicenseId() ?>;
  if(livechat_visitor_data) {
    window.__lc.visitor = livechat_visitor_data;
  }

  (function() {
    var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
    lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
  })();

  <?php if ($block->isCartSet()): ?>
    var LC_API = LC_API || {};
    LC_API.on_after_load = function() {
        require(['Magento_Customer/js/customer-data'], function (customerData) {
            var cart = customerData.get('cart');
            var count = cart().summary_count;

            if(localStorage) {
              var storageCount = localStorage.getItem('lcCount');
              if(parseInt(storageCount) !== count) {
                getCart();
              }
              localStorage.setItem('lcCount', count);
            }

            var count = cart().summary_count;
            cart.subscribe(function () {
                if (cart().summary_count !== count) {
                    getCart();
                    if(localStorage) {
                      localStorage.setItem('lcCount', cart().summary_count);
                    }
                }
            });
        });
    }

    function getCart() {
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            var customVariables = JSON.parse(this.responseText);

            if (customVariables.length <= 0) {
                customVariables = [{"name":"Cart", "value":"customer's cart is empty"}];
            }

            LC_API.set_custom_variables(customVariables);
        }
      };
      xhttp.open("GET", "<?php echo $block->getUrl('livechat/getcart'); ?>"+"?success=<?php echo $block->isOrderPlacedPage() ?>", true);
      xhttp.send();
    }

  <?php endif; ?>
</script>
<?php else: ?>
<script>
  console.log('Please go to "Stores => Settings => Configuration" and configure your LiveChat account.');
</script>
<?php endif; ?>
