<div id="login_panel" style="align-items: center; <?php echo $block->getLicenseId() > 0 ? 'display: none;' : ' display: flex;' ?>">
	<div style="display: flex; flex-direction: column; align-items: center; margin-bottom: 40px;">
		<div style="display: flex; flex-direction: row; align-items: center;">
		<img src='<?php echo $this->getViewFileUrl('LiveChat_LiveChat::img/livechat-magento@2x.png'); ?>' alt="Demo" class="livechat_logo2" >
		</div>
		<div id="login_form">
		<div class="progress-button hidden">
			Saving...
		</div>
		<div>
			<iframe id="login-with-livechat" src="https://addons.livechatinc.com/sign-in-with-livechat/magento2?popupRoute=signup&linkLabel=Connect&partner_id=magento2&utm_source=magento.com&utm_medium=integration&utm_campaign=magento_integration"> </iframe>
		</div>
		</div>
	</div>
</div>
<div id="admin_panel" style="<?php echo $block->getLicenseId() > 0 ? 'display: block;' : 'display: none;' ?>" >
	<div id="livechat_panel">
		<div style="max-width: 100%;">
			<div class="entry-edit-head admin__collapsible-block arrow-hidden"><span id="lc_block_config_custom_params-link" class="entry-edit-head-link"></span><a id="lc_block_config_custom_params-head" style="pointer-events: none;" href="# return false;" class="open">Your LiveChat is now ready!</a><img src='<?php echo $this->getViewFileUrl('LiveChat_LiveChat::img/livechat.png'); ?>' alt="livechat_logo" style="display: inline-block; margin-right: 100px; float: right;"></div>
		<div>You are now rocking chat window from your <span id="livechat_login" style="font-weight: bold;"><?php echo $block->getLicenseEmail(); ?></span> account.</div>
		<p>
			<a target="_blank" href="https://www.livechatinc.com/product/">Download desktop app</a> or
			<a target="_blank" href="https://my.livechatinc.com/">use our WebApp</a>.</p>
		<div class="section-config active" style="margin-top: 30px;">
			
			<p>Need help? <a href="https://www.livechatinc.com/kb/magento-livechat-integration?partner_id=magento2&utm_source=magento.com&utm_medium=integration&utm_campaign=magento_integration" target="_blank">Click here</a> to check out our integration tutorial.</p>
			<div class="entry-edit-head admin__collapsible-block"><span id="lc_block_config_custom_params-link" class="entry-edit-head-link"></span><a id="lc_block_config_custom_params-head" href="#lc_block_config_custom_params-link" onclick="Fieldset.toggleCollapse('lc_block_config_custom_params'); return false;" class="open" style="padding-top: 9px; padding-bottom: 0px;">Custom parameters</a></div>
			<input id="lc_block_config_custom_params-state" type="hidden" value="1">
			<fieldset class="config admin__collapsible-block" id="lc_block_config_custom_params">
				<legend>Custom parameters</legend>
				<div class="comment" style="margin-top:8px;">Enable custom parameters to display additional information about your customers	and their purchases directly in your LiveChat.</div>
				<table cellspacing="0" class="form-list">
					<tbody>
					<tr>
						<td style="padding-right:15px;" class="label"><label for="lc_block_config_custom_params_cart_products"><span data-config-scope="[STORE VIEW]">Cart products</span></label></td>
						<td class="value">
							<select id="lc_block_config_custom_params_cart_products" class="select admin__control-select">
								<option value="1" <?php echo ($block->isSetCartProducts() == true ? 'selected="selected"' : '')?>>Enable</option>
								<option value="0" <?php echo ($block->isSetCartProducts() == true ? '' : 'selected="selected"')?>>Disable</option>
							</select>
							<p class="note"><span>See what a customer has in his cart.</span></p>
						</td>
						<td class="">
						</td>
					</tr>
					<tr>
						<td style="padding-right:15px;" class="label"><label for="lc_block_config_custom_params_total_cart_value"><span data-config-scope="[STORE VIEW]">Total cart value</span></label></td>
						<td class="value">
							<select id="lc_block_config_custom_params_total_cart_value" class="select admin__control-select">
								<option value="1" <?php echo ($block->isSetTotalCartValue() == true ? 'selected="selected"' : '')?>>Enable</option>
								<option value="0" <?php echo ($block->isSetTotalCartValue() == true ? '' : 'selected="selected"')?>>Disable</option>
							</select>
							<p class="note"><span>Know the value of products currently in the cart.</span></p>
						</td>
						<td class=""></td>
					</tr>
					<tr>
						<td style="padding-right:15px;" class="label"><label for="lc_block_config_custom_params_total_orders_count"><span data-config-scope="[STORE VIEW]">Total orders</span></label></td>
						<td class="value">
							<select id="lc_block_config_custom_params_total_orders_count" class="select admin__control-select">
								<option value="1" <?php echo ($block->isSetTotalOrdersCount() == true ? 'selected="selected"' : '')?>>Enable</option>
								<option value="0" <?php echo ($block->isSetTotalOrdersCount() == true ? '' : 'selected="selected"')?>>Disable</option>
							</select>
							<p class="note"><span>See how many orders a customer has placed with you in the past.</span></p>
						</td>
						<td class=""></td>
					</tr>
					<tr>
						<td style="padding-right:15px;" class="label"><label for="lc_block_config_custom_params_last_order_details"><span data-config-scope="[STORE VIEW]">Last order details</span></label></td>
						<td class="value">
							<select id="lc_block_config_custom_params_last_order_details" class="select admin__control-select">
								<option value="1" <?php echo ($block->isSetLastOrderDetalils() == true ? 'selected="selected"' : '')?>>Enable</option>
								<option value="0" <?php echo ($block->isSetLastOrderDetalils() == true ? '' : 'selected="selected"')?>>Disable</option>
							</select>
							<p class="note"><span>See when a customer placed or updated their last order, it's grand total, status and state.</span></p>
						</td>
						<td class=""></td>
					</tr>
					</tbody>
				</table>
			</fieldset>
		</div>
		
		<p class="reset-settings">Something went wrong? <a class="reset-settings" href="#" id="reset_settings">Click here</a> to reset settings!</p>
		</div>
	</div>
</div>
<div id="save-props-url" hidden><?php echo $block->getUrl('livechat/setprops');?></div>
<div id="save-license-url" hidden><?php echo $block->getUrl('livechat/setlicense');?></div>
<div id="reset-license-url" hidden><?php echo $block->getUrl('livechat/resetlicense');?></div>
<div id="get-props-url" hidden><?php echo $block->getUrl('livechat/getprops');?></div>
<div id="licenseId" hidden><?php echo $block->getLicenseId();?></div>